function mp_strct = assemble_constraint_sys(mp_strct)
    hD = [];
    for i=1:numel(mp_strct.patch_arr)
        %% Assemble and Save the matrix and vector
        Bi = sparse(mp_strct.patch_arr(i).rowsBi,...
                     mp_strct.patch_arr(i).colsBi,...
                     mp_strct.patch_arr(i).dataBi,...
                     mp_strct.numMultiplier,...
                     mp_strct.patch_arr(i).space.ndof);
        BDi = sparse(mp_strct.patch_arr(i).rowsBDi,...
                     mp_strct.patch_arr(i).colsBDi,...
                     ones(size(mp_strct.patch_arr(i).colsBDi)),...
                     mp_strct.cumu_bnd_dofs(end),...
                     mp_strct.patch_arr(i).space.ndof);
        mp_strct.patch_arr(i).Bi = [BDi;Bi];
        hD = [hD;mp_strct.patch_arr(i).hDi];
    end
    mp_strct.h = [hD;spalloc(mp_strct.numMultiplier,1,0)];
    mp_strct.numMultiplier = numel(mp_strct.h);
end